apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardmetrics.fullname" . }}-jwt
  labels:
    {{- include "guardmetrics.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.jwt.secretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardmetrics.fullname" . }}-virustotal
  labels:
    {{- include "guardmetrics.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.virustotal.apiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardmetrics.fullname" . }}-telegram
  labels:
    {{- include "guardmetrics.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.secrets.telegram.botToken | b64enc | quote }}
  chat-id: {{ .Values.secrets.telegram.chatId | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardmetrics.fullname" . }}-secrets
  labels:
    {{- include "guardmetrics.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc | quote }} 